name: Deploy (Prod)
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: prod
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies, build and reload pm2 process
        run: |
          echo Installing dependencies...
          cd prod
          npm ci
          echo Setting environment variables...
          touch .env
          echo LOGIN_TOKEN=${{ secrets.LOGIN_TOKEN }} >> .env
          echo LOL_DDRAGON_URL=${{ secrets.LOL_DDRAGON_URL }} >> .env
          echo CHANGELOG_PATH=${{ secrets.CHANGELOG_PATH }} >> .env
          echo Building...
          npm run build
          echo Reloading...
          pm2 reload ojk-discord-bot
