name: Deploy
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: beta
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        run: |
          echo Installing dependencies...
          npm ci
      - name: Set environment variables
        run: |
          echo Setting environment variables...
          touch .env
          echo ${{ secrets.LOGIN_TOKEN_BETA }} >> .env
          echo ${{ secrets.LOL_DDRAGON_URL }} >> .env
          echo ${{ secrets.CHANGELOG_PATH_BETA }} >> .env
      - name: Build
        run: |
          echo Building...
          npm run build
      - name: Reload pm2 process
        run: |
          echo Reloading...
          pm2 reload ojk-discord-bot-beta
