name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true
      - name: Deploy
        run: |
          echo Installing dependencies...
          npm install
          echo Setting environment variables...
          echo ${{ secrets.LOGIN_TOKEN }} >> .env
          echo ${{ secrets.LOL_DDRAGON_URL }} >> .env
          echo ${{ secrets.CHANGELOG_PATH }} >> .env
          echo Building...
          npm run build
          echo Reloading...
          pm2 reload ojk-discord-bot
