name: Deploy
on:
  push:
    branches:
      - actions-testing
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Deploy
      run: |
        echo Installing dependencies...
        npm install
        echo Setting environment variables...
        echo ${{ secrets.ENV }} > .env
        echo Building...
        npm run build
        echo Reloading...
        pm2 reload ojk-discord-bot
